my_games:
    resource: "@MyGamesBundle/Resources/config/routing.yml"
    prefix:   /

my_home_page:
    resource: "@MyHomePageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
