home:
    path:     /
    defaults: { _controller: MyHomePageBundle:Home:index }

cv:
    path:   /cv
    defaults: { _controller: MyHomePageBundle:Cv:index }
    
portfolio:
    path:   /portfolio
    defaults: { _controller: MyHomePageBundle:Portfolio:index }
    
contact:
    path:   /contact
    defaults: { _controller: MyHomePageBundle:Contact:index }
    
admin:
    path: /admin
    defaults: { _controller: MyHomePageBundle:Admin:index }

upload:
    path: /admin/upload
    defaults: { _controller: MyHomePageBundle:Admin:upload }