My\HomePageBundle\Entity\Site:
    properties:
        name:
            - NotBlank: ~
        description:
            - NotBlank: ~
        link:
            - NotBlank: ~
        file:
            - Image: ~
            
My\HomePageBundle\Entity\Technology:
    properties:
        description:
            - NotBlank: ~
        